apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx
        image: {{ .Values.webserver.image }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 4096Mi
