eplicaCount: 1
image:
  repository: repo
  tag: latest
  pullPolicy: IfNotPresent

jsonEndpoint: ""

service:
  type: ClusterIP
  port: 7979
  annotations: {}

prometheus:
  serviceMonitor:
    enabled: true
    interval: "30s"
    additionalLabels: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
