apiVersion: v1
kind: Service
metadata:
  name: {{ template "json-exporter.fullname" . }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  labels:
    app: {{ template "json-exporter.name" . }}
#    chart: {{ template "json-exporter.chart" . }}
    release: {{ .Release.Name }}
#    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: json-port
      protocol: TCP
      name: http
  selector:
    app: {{ template "json-exporter.name" . }}
    release: {{ .Release.Name }}
